### ISSUE TITLE
Barplots of class enrollment data

### ISSUE THREAD

**Issue by hui-tony-zk** [STAT545-UBC/Discussion#112]
It was suggested in class to make some plots of the STAT 545 enrollment data.

<a href="https://github.com/STAT545-UBC/tony_hui/tree/master/random_class_stuff/Enrollment_barplots" target="_blank">I did it here</a>

@jennybc will more data be released? Maybe from previous years?

**Comment by daattali** [comment]
That is awesome Tony, really nice. My only big suggestion for improvement would be to re-order the departments such that in each bar plot, the bars are increasing or decreasing from side to side , rather than being all over the place (right now order is alphabetical).  In [cm12](http://stat545-ubc.github.io/syllabus.html) we'll learn everything about factors and how to do this (though I'm sure you yourself can figure it out if you care to)

I just google'd for the 2013 offering and [in the intro slides](http://www.stat.ubc.ca/~jenny/STAT545A/2013-lectures/cm01_intro-to-course.pdf) on slides 67-68 she has similar data for 2011 and 2012. Looks like the course was dominated by stats in 2011

**Comment by hui-tony-zk** [comment]
@daattali Done as recommended. 

Would be cool to get more (anonymized) data regarding each student. Could potentially find more trends.

**Comment by daattali** [comment]
It *would* be cool to be able to plot final mark vs department, but I doubt we're allowed to get that info, even anonymized.  

We do have a bit of data (OS type, IDE used) from the form you guys submitted last week, but I'm not sure we're allowed to release that, @jennybc will have to make that call. Though it's super interesting.

**Comment by BernhardKonrad** [comment]
Is it just me or does the link not work any more?

**Comment by daattali** [comment]
just you.. still works

**Comment by jennybc** [comment]
Can't do it now but I have datasets over many years. Will try to put up. Or get @daattali to clean it and do it :grin:

**Comment by daattali** [comment]
@hui-tony-zk @jennybc 
I took a list that I found in the private instructors repository and anonymized it and cleaned it a bit.
[Available in the main course website repo](https://github.com/STAT545-UBC/STAT545-UBC.github.io/blob/master/course-admin/history/STAT545-registered-students-all-time-anonymized.csv)

**Comment by hui-tony-zk** [comment]
@daattali @jennybc 

Done - have a look at [the same page as before](https://github.com/STAT545-UBC/tony_hui/tree/master/random_class_stuff/Enrollment_barplots). Adding an extra dimension (Gender) really made things much more "alive"

By the way, can I use this as hw2 instead of my [current hw2](https://github.com/STAT545-UBC/tony_hui/tree/master/Homeworks/Homework_2)? Gapminder data is boring

**Comment by jennybc** [comment]
Nice work @hui-tony-zk!

Certainly link to it from your HW02 but don't actually substitute since you should also be submitting plots with a quantititative variable, i.e. not just barplots.
