### ISSUE TITLE
Technology overload?

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#114]
I found a bit overwhelmed by all these apps/websites that help us backup our files. I have been using Dropbox for a long time. I need it for sharing stuff with my supervisor. Then the Open Science Framework came along. Now our lab has to use that for sharing articles and other things. At some point, my friend was teaching me how to use BitBucket.. And now I am using GitHub for this course. Do most of you are also using so many similar things at the same time..?  How do you manage all these different apps/accounts?

**Comment by daattali** [comment]
Short answer: yes, many of us do use multiple applications, though I rarely think about it because you'll get more efficient at it and it'll seem natural, and you might naturally start moving away from some of these applications in favour of the ones that best suit your needs.  It's true that there are lots of accounts, but I think that's just an inevitable part of technology being so fast these years and a big part of using technology is being able to learn about the new things every few months and re-adapt your workflow to be more efficient as new things come. GitHub for example is only several years old but it already is used by countless companies and individuals because it really allowed tons of people to be much more efficient in writing and sharing and collaborating. 

(The same can be said about communicating with your friends: 10 years ago it was super simple: phone. Then all of a sudden we have facebook, twitter, instagram, whatsapp, messaging, email, ... it can seem overwhelming, but everyone learns how they work best with all of them together)

I have a dropbox account and use it to store some personal files and to share files (pictures/videos/random files) with people. I extensively use GitHub too but for a different purpose: for projects and documents. If I want to share code/reports/text documents, then I put it on GitHub (and this can replace Dropbox for sharing stuff with your supervisor).   BitBucket is not really needed since you're using GItHub - they're very similar, but are big rivals.  I think GitHub is winning, you can read online about "github vs bitbucket", but they generally do the same thing and many people agree that GitHub is doing it better. The one big plus in BitBucket is that they give you unlimited private repositories.

So it might feel overwhelming whenever you get introduced to a new tool just because it's new and scary and unfamiliar, but hopefully you'll find very fast what the usecase of each tool is and it'll be very natural to decide what to use.

Hope that helped

**Comment by BernhardKonrad** [comment]
I like the analogy about communicating with friends. Now *that's* overwhelming for me :)

I suggest you give all of these tools a fair shot and see which works best for which parts of your work.

**Comment by jennybc** [comment]
@cathyxijuan Good question and really good answers. I don't really have any wisdom to add.

**Comment by npjc** [comment]
@cathyxijuan 

My `2 * (dollar/100)`:

I very much value integration so I don't have to think about which things are where. This means when I try out something new I try and be ruthless about at least one of these two things being `TRUE`:
1. Does it increase my ability to solve/achieve x.
2. Does it increase the redundancy in my life without adding complexity (more redundancy is good if it comes for free; servers are susceptible to shark attacks too right?).

I also think that everything in my life is a _project_. This is the top-most organizational 'bucket' in my life. If I subscribe to this model then all I have to keep tabs on is what systems each _project_ touches:
- An R package might only touch github.
- A manuscript (which say contains multiple projects: 
Google-Genomics Cloud platform container for storing data and processing methods a github repo of the written sections (intro, results, figs, discussion)  a github repo of an R package which contains pipeline to make the figures and 

For Example to store your files you have: 
local machine, Github, Dropbox, Google Drive, Google Cloud Storage, iCloud, etc...

Figure out which is suits best. I, for example,

**Comment by cathyxijuan** [comment]
Thank you very much for everyone's valuable answers! I really appreciate it.
