### ISSUE TITLE
figures in the rmarkdown file

### ISSUE THREAD

**Issue by wang114** [STAT545-UBC/Discussion#119]
It seems that when I change the content in the curly breaks of a r chunk in the rmd file, the figures produced from that chuck of code get renamed and saved again when I click html. I ended up having more figures in the file folder than I actually need.  Should I keep all of them? Or I can delete the unnecessary ones?

**Comment by cathyxijuan** [comment]
I think it depends on whether you think you will it the files

**Comment by jennybc** [comment]
As long as you are saving and commiting your R markdown file reguarly , you can never harm yourself by deleting the directory of figures and re-running "Knit HTML". This is an example of "clean out everything and remake from scratch" and it's a good idea to do this regularly, in many settings. It will teach you to save **code** more carefully than results. Of course we save results -- it is convenient! -- but as long as you have the data and code, you can always reproduce everything. And it's useful for making sure you are not saving stuff that is out-of-date debris and will only confuse you later.

**Comment by jennybc** [comment]
Also the "content in the curly breaks of an r chunk" are the **chunk options**. If you include a chunk name there, that should stabilize the name(s) for the figure(s) produced by the associated chunk.

Look at the chunks here that produce figures:

https://raw.githubusercontent.com/STAT545-UBC/STAT545-UBC.github.io/master/block006_care-feeding-data.rmd

You'll see I generally name figure-producing chunks and this is exactly so that the resulting figures get decent and stable names:

https://github.com/STAT545-UBC/STAT545-UBC.github.io/tree/master/block006_care-feeding-data_files/figure-html
