### ISSUE TITLE
[Time Sensitive] Hadley Wickham AMA!

### ISSUE THREAD

**Issue by samhinshaw** [STAT545-UBC/Discussion#121]
Starts in ~10min at 12pm.

https://www.reddit.com/r/dataisbeautiful/comments/3mp9r7/_/

**Comment by hui-tony-zk** [comment]
I took a look, and jot down some questions I was wondering about Data Science. Perhaps @jennybc, @daattali, @ksamuk or other TA's can offer some insight?

**People (and Hadley) discussing the [Grammar of Modelling](https://www.reddit.com/r/dataisbeautiful/comments/3mp9r7/im_hadley_wickham_chief_scientist_at_rstudio_and/cvh6k7f)** 

* How does modelling currently work in R? What are the pain points? Seems like people are tired of it and want something better

**Hadley summarizes [what he thinks of big data](https://www.reddit.com/r/dataisbeautiful/comments/3mp9r7/im_hadley_wickham_chief_scientist_at_rstudio_and/cvgyojt)**

* He mentions Hadoop for scaling to large computations - a quick google tells me that it's a distributed something something. Are we ever going to touch on this? Seems very important for Data Scientists (I recall every job posting ever mentioning something about Hadoop)
* He mentions "distributed database (like hive, impala, teradata etc)" - what are these? I'm assuming relevant to Hadoop?
* Hadley mentions [redshift](https://www.reddit.com/r/dataisbeautiful/comments/3mp9r7/im_hadley_wickham_chief_scientist_at_rstudio_and/cvh5uik) and dplyr. The comment he is replying to mentions something about PostreSQL. What are these?

**Hadley says [how much better he likes working at RStudio over Rice University](https://www.reddit.com/r/dataisbeautiful/comments/3mp9r7/im_hadley_wickham_chief_scientist_at_rstudio_and/cvgyzgc)**

* There goes my academic aspirations.

**Some discussion regarding [Julia as a replacement for R](https://www.reddit.com/r/dataisbeautiful/comments/3mp9r7/im_hadley_wickham_chief_scientist_at_rstudio_and/cvgvuwv)**

* Will Data Science switch to Julia to the future, just like how people hopped from Perl to Python?
* Hadley says if he starts over again, [he'd use Julia or Python over R](https://www.reddit.com/r/dataisbeautiful/comments/3mp9r7/im_hadley_wickham_chief_scientist_at_rstudio_and/cvh853m)

**Hadley mentions [ggvis and htmlwidgets](https://www.reddit.com/r/dataisbeautiful/comments/3mp9r7/im_hadley_wickham_chief_scientist_at_rstudio_and/cvgz410) for the future of interactive plots**

* Are we going to be touching on these tools during the "shiny" development? Any resources for me to look into to learn more?

**Seems like people want a [GUI around R](https://www.reddit.com/r/dataisbeautiful/comments/3mp9r7/im_hadley_wickham_chief_scientist_at_rstudio_and/cvh9gxo), like SAS**

* [Jasp](https://jasp-stats.org/) seems super cool
* Some good points regarding reproducible science - wrapping a GUI around R seems to make things more "streamlined" since there's only so much one can do.

**Comment by daattali** [comment]
Hey Tony, I'll just answer a select few comments:

- I highly doubt we'll touch on distributed computing, it's more advanced and will likely not be useful to most students in this course with their theses. I'm sure there are some UBC courses in computer science, or coursera courses or just good online tutorials to learn these things

- Looks like Julia is gaining popularity, but I wouldn't say that it'll take over R any time soon. R itself is also gaining popularity, and the sheer number of packages and the great community and resources associated with it are going to be very hard to beat and take a long time to re-create in Julia

- I believe Hadley meant that if R didn't exist and he would start now, then he would use Julia/Python. I don't think he meant that he would use python/julia right now if R still existed as well.

- We probably won't be covering ggvis and htmlwidgets. `ggvis` is kind of like the next version of ggplot2 but with different syntax and more web-y, which is why it lends itself nicely to shiny, but it's not necessarily for shiny. If you already know ggplot2, you can learn ggvis very easily in about 20 minutes. Just read the official docs on RStudio's website for ggvis. It's not hard at all.  `htmlwidgets` is a fairly advanced topic in shiny andd very few people need to actually use it, if you want to learn it I would just go to their website (99% of R packages don't have a website or official tutorials, but these two packages do, so use them).  But you'd need to understand shiny fairly well before that.  I don't think you should bother with htmlwidgets until you're very comfortable with shiny and have a specific need that would be solved with it

- I personally don't think a GUI is neessary. R is a programming language, and IMO having a GUI goes completely against being a programming language. A GUI is all about exposing a specific set of features, so it has to be very restrictive and it makes the user only be able to perform the few functions that the GUI allows. Shiny can be used to create GUI if you have specific functionality you want to expose or specific code you want to make available for people without exposing them to the scary world of "programming"/command line. But a general GUI for all of R would be weird. There are programs that do similar statistical analysis that are based completely on GUI, for example JMP, and I personally HATE that it's all GUI based because it takes away a lot of flexibility and you have to know exactly what buttons to click to do what you want.  

I hope my answers make sense.

**Comment by cathyxijuan** [comment]
Omg this is so cool! I didn't see this post earlier.. I am guessing the AMA is over now?

**Comment by hui-tony-zk** [comment]
@daattali I'd argue that what Hadley is doing with his packages (ggplot, dplyr, stringr, tidyr) are also about "exposing a specific set of features." i.e. tailored to the (*made up number here*) 90% of use cases.

If you wrap a GUI around the hadley packages with intuitive drag-n-drop (filter this, arrange this, mutate this) and made it easy to for people to chain commands together like a skewer:

<img src="http://www.eatingutensils.net/images/27/skewer-1.jpg">

AND include a script/console within it, I'd argue that this would be much more powerful than just straight command line, and make Data Science more accessible to non-computer scientists.

**Comment by jennybc** [comment]
@daattali gave some great answers. Will try to bat clean-up.

* How does modelling currently work in R? What are the pain points? Seems like people are tired of it and want something better

  - I think this refers to the historical lack of a common front-end for modelling. Which is what `caret` and `mlr` aim to improve. And the dust is far from settled. Hence the continuing conversation and development.

* The big data, Hadoop stuff. And the ggvis, htmlwidgets stuff.

  - This reminds me of a quote I use in STAT 540, where I have taught stats for genomics:

        > “Using fancy tools like neural nets, boosting, and support vector machines without understanding basic statistics is like doing brain surgery before knowing how to use a band-aid.” -- Larry Wasserman in All of Statistics

    In STAT 545 we're concentrating on cultivating the basic skills that come before distributed and cloud computing. Which fewer people need than the hype will lead you to believe. Even if you are eventually headed for this level and type of data work, you need to lay a foundation with smaller and simpler problems and tools.

This is not meant to discourage anyone from trying some of this stuff, even in your coursework! In particular, some people may want to experiment with interactive visualizations. But this is why it's not core curriculum that I would inflict on everyone at this time.

**Comment by kenmansfield** [comment]
EECE 571B is the "Big Data" course that touches on systems such as Hadoop (as far as I know the only course at UBC). 

I'm interested in Data Science as well, aside from this course (and the big data course), what other courses would be useful? Should I be taking STAT 540?

**Comment by jennybc** [comment]
STAT 540 is overtly focused on genomics. That said, it gives very good coverage of a wide array of statistical techniques that come up in all sorts of areas. Since we don't offer other similar stat courses at the grad level (i.e. aimed at non-stat grad students who are motivated and just want to learn or refresh the most important things), it's not entirely crazy to take it, even if you're not interested in genomics.

Would also recommend machine learning (can't remember course number ... and it might be joint between CS/STAT?) and data vis (Tamara Munzner's course ... but might be limited to CS students?).

**Comment by hui-tony-zk** [comment]
Cpsc 340 is the super popular machine learning course
https://www.cs.ubc.ca/~schmidtm/Courses/340-F15/. Dr. Schmidt also has
recommendations for related courses on that website.

Cpsc 540 is the graduate version, but that course expects strong
quantitative background, since they dive into theory and proofs.
https://www.cs.ubc.ca/~schmidtm/Courses/540-W16/ has a discussion on the
differences.

**Comment by jennybc** [comment]
Thanks @hui-tony-zk those are exactly the machine learning courses I was thinking of. Yes, the grad version is quite intense -- it can be very rewarding but very time-consuming, I hear.

Tamara's course is [CPSC 547: Information Visualization](https://www.cs.ubc.ca/~tmm/courses/547-15/). It looks like there are seats for non-CS grad students.
