### ISSUE TITLE
problem with push and pull

### ISSUE THREAD

**Issue by farnushfarhadi** [STAT545-UBC/Discussion#126]
Hi all, 

I have written my .rmd file but I can not push it to my repo in GitHub. Push and Pull buttons are inactive in my Rstudio. I also see that my 'HEAD is detached from origin/master'. 

Can anyone help please?

Thanks, 
Farnush

**Comment by jennybc** [comment]
OK somehow you have gotten into the "detached HEAD" state. I don't much want to fix this via this conversation, because it seems easy for us to miscommunicate.

Here is the lowest tech thing you could do. Let me know if you feel comfortable with this.

Using non-Git methods, make a copy of the directory where your course repo lives. Make this a copy on your local computer. Make sure it looks exactly like you want it to. Make sure all the important Markdown and R markdown files are backed up!

Then, and only then:

Delete your local Git repo for the course (note the copy you have made above!).

Re-do the [claim your STAT545 repository](http://stat545-ubc.github.io/git08_claim-stat545-repo.html) steps. That is, re-clone the content you have on GitHub to your local computer.

Again, using non-Git methods, but just your OS, common sense, etc. restore the new course repo to how it should be, using the copy made above. You are manually restoring things to the state you want. Commit. Push.

There are much more official Git ways to do this but this is honestly your best move if you want to fix this quickly.

**Comment by farnushfarhadi** [comment]
Thank you very much. It helped.

**Comment by bdacunha** [comment]
I'm not sure I feel comfortable doing it. Don't know how to create a copy of the directory (is it just a regular copy? like copying the file and pasting it somewhere else?).

**Comment by jennybc** [comment]
@bdacunha This wasn't necessarily directed at you (your issue is #120), though it's possible the same fix would work. It sounds like maybe you should wait til one of us can sit with you then. You already submitted HW2, right? So you can wait til tomorrow?

**Comment by daattali** [comment]
@bdacunha you should come to office hours if you can , it's always easiest to help with these sorts of problems in person.  Office hours are always right after class

**Comment by bdacunha** [comment]
Yes, I already submitted my homework 2... I wanted to go to office hours, but I have a class from 11-12 on Tuesdays and Thursdays... maybe tomorrow I can just be a little late to class I guess...

**Comment by jennybc** [comment]
There will likely be some "work on your own" time during class when we might able to resolve this.
