### ISSUE TITLE
Ordered list numbers are reset to 1. after each plot/table

### ISSUE THREAD

**Issue by hochoy** [STAT545-UBC/Discussion#139]
Hi @jennybc ,

I finished working on homework 3, previewed it in Rstudio (.html) and my ordered lists looked fine. But after pushing it to github, my ordered lists reset to 1. after any new plot or table. I had a look at the raw code in the .Rmd and .md file and my numbers are ordered correctly (1., 2.,plot, 3.,,table 4.,...) but is displayed as (1., 2., plot, 1.,table, 1.,...)

~   1. line 1
~   2. line 2
~   plot
~   3. line 3
~   table
~   4. line 4

becomes (after github):

~   1. line 1
~   2. line 2
~   plot
~   1. line 3
~   table
~   1. line 4

My homework is [here](https://github.com/STAT545-UBC/wai-ho_choy/blob/master/Homework_3/Homework3.md)

**Comment by jennybc** [comment]
Without mounting my own Google campaign .... I'm not exactly sure what's going on. My instinct is that you have extra whitespace or something, that's making these look like separate but adjacent numbered lists, hence the re-starting from 1. The fact that you see the numbers correctly in the markdown means nothing, because the numbers in a numbered list in Markdown mean nothing. The numbering is done upon conversion to HTML. So you're getting the desired behavior with RStudio's md --> html conversion, but not with GitHub's. I realize this doesn't help you but maybe moves the conversation along ...
