### ISSUE TITLE
question about operator

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#161]
I knew we went over this in Tuesday's class.. But I  just forgot. 
What is %T>%  mean?

**Comment by molliejmcdowell** [comment]
This isn't an answer to your question (sorry) but an expansion of this question... 
When do we use characters other than > inside the pipe operator? 
Especially %in% and %T>%.
How do we know when to use other characters?

**Comment by eacton** [comment]
@cathyxijuan  %T>% is the tee operator from magrittr - it allows you to pipe a value on the left to a function on the right (like with %>%) , but it returns the value on the left rather than the output. It is most often used when you have a plotting statement on the right, or something that you don't need to see or might want to pass over when coding. Consider the following example:

This statement will print gapminder rather than the plot.
gapminder %T>% qplot(lifeExp, pop) 

This statement will give the mean lifeExp.
gapminder %T>% qplot(lifeExp, pop) %>% summarise(mean(lifeExp))

And this statement will give an error because you can't pass a plot to summarise.
gapminder %>% qplot(lifeExp, pop) %>% summarise(mean(lifeExp))

**Comment by daattali** [comment]
To answer the original question:  `%T>%` is from the `magrittr` package. You can [read here](https://github.com/smbache/magrittr#tee-operations) about it.  From the README:

> Some right-hand sides are used for their side effect (e.g. plotting, printing to a file, etc) and it may be convenient to be able to subsequently continue the pipeline. The "tee" operator, %T>% can be used for this purpose and works exactly like %>%, except it returns the left-hand side value, rather than the potential result of the right-hand side operation.

To use `%T>%` you must first load the `magrittr` package.


The next question: `%in%` is a base R operator, meaning that you don't need to import any special package - it's built into R.  `magrittr` has several other operators that use the percent-sign syntax (which you can read about in the README that I linked to above), but `%>%` is the one used most commonly, and it's good to know about `%T>%` as well.  As far as builtin R functions go, `%in%` is the most commonly used one.  There's no complete way to just "know" all the possibilities, because it's just like any other function - you just need to know of its existence. But I can tell you right now that `%in%` and `%>%` are probably by far the most commonly used operators with this syntax.

[This page](http://adv-r.had.co.nz/Vocabulary.html) has a list of common R functions that people should know, so you can look there to see what the common basic functions are.

TMI: these functions are called infix functions, you can read more about that [here](http://adv-r.had.co.nz/Functions.html#special-calls) if you're interestered
