### ISSUE TITLE
making a list into a data.frame

### ISSUE THREAD

**Issue by JoeyBernhardt** [STAT545-UBC/Discussion#166]
Hi all,

I'm trying to write a function and apply to multiple groups in my dataset using do(), and the outputs are in list form. I'd like to somehow turn those all those lists into a data.frame, but I get an error b/c the elements don't have the same length (i.e. I have different numbers of observations for each grouping variable). 

@jennybc says: 
'You will encounter weirder situations in which you want to make a data.frame out of a list and there are many tricks. Ask me and we’ll beef up this section.'

on this page from our class site:
http://stat545-ubc.github.io/block004_basic-r-objects.html#lists-hold-just-about-anything

Any tips?? Thanks!

I tried something like this: epa.prp <- as.data.frame(lapply(epa.prp, unlist))  but get this error:

Error in data.frame(taxon = c(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L,  : 
  arguments imply differing number of rows: 26, 9378

**Comment by jennybc** [comment]
I'm afraid I would need more specifics in order to help :disappointed:.

It will never work to make a data.frame out of things that have different lengths.

Instead, it sounds to me like you need to make data.frames for each group *that have the same variables* but possibly different numbers of rows. Then `do()` should rowbind them for you. But I may be misunderstanding your problem.

**Comment by AdrianLJones** [comment]
Are you talking about an output of list columns from `do()` as was mentioned in class?  I discovered that there is a function `tidyr::unnest` that will turn a list column into a normal data.frame.  Maybe that will help?

**Comment by JoeyBernhardt** [comment]
Yes! Thanks so much @AdrianLJones that worked for what I wanted to do!
