### ISSUE TITLE
simple mapping in R?

### ISSUE THREAD

**Issue by SarahUBC** [STAT545-UBC/Discussion#180]
Can you recommend the best tools in R and/or ggplot to map latitude and longitude coordinates? 

The first hit on google is this link: http://zevross.com/blog/2014/07/16/mapping-in-r-using-the-ggplot2-package/

and I also saw this:
http://www.milanor.net/blog/?p=594

I was wondering if any of you have experience with these tools. Are there other tips, tools or packages that can make mapping easier in R? I already know ArcGIS and QGIS and am curious to experiment with making maps in R. 

Thanks,
Sarah

**Comment by ksamuk** [comment]
I've done a bit of mapping R using maps/maptools/ggplot. I found this tutorial by Kim Gilbert (currently in the zoology dept.) very useful:

http://www.molecularecologist.com/2012/09/making-maps-with-r/

You might also check out the ggmap package here: https://cran.r-project.org/web/packages/ggmap/index.html

If you're doing marine/bathymetric mapping I highly highly recommend marmap: https://cran.r-project.org/web/packages/marmap/index.html

**Comment by mstrimas** [comment]
I think the best package depends a lot on exactly what you're trying to do. The `maps` package in Kim's tutorial is great if you want to incorporate existing administrative boundaries (countries, states, counties). The [`ggmap`](https://github.com/dkahle/ggmap) package is cool if you want to plot data on top of map tiles from Google Maps or Open Street Maps. For plotting raster data I like the [rasterVis](http://oscarperpinan.github.io/rastervis/) package. I typically use the `spplot()` function from the `sp` package for vector data, largely because it plays well with `rasterVis` and most of my mapping includes rater data.  The downside of these packages is that they're based on `lattice` graphics and I often find them to be cumbersome to use.  

You can also use `ggplot2` to [plot points, lines, and polygons](http://spatial.ly/2013/12/introduction-spatial-data-ggplot2/), but it requires some work to process the data into a format that `ggplot()` can understand since, as far as I know, it can't handle spatial objects directly.

Finally, if you're not already familiar with them, the packages `sp` and `raster` define R's spatial data classes. It might be worth reading up about these packages since importing a shapefile or raster file into R will likely result in an object defined by these packages. For example, there are some tutorials and a cheat sheet [here](http://www.maths.lancs.ac.uk/~rowlings/Teaching/UseR2012/index.html). The functions also define base `plot()` function can plot vector or raster data, although it generally doesn't look super nice.
