### ISSUE TITLE
Why my ggsave() works in code-running but fails when kniting HTML?

### ISSUE THREAD

**Issue by BattaLiu** [STAT545-UBC/Discussion#192]
I use ggsave() to save my graph using in the same directory as my HW5.Rmd, and it is saved when I run the code. However, when I want to knit HTML, an error stops the process:

Error in dev.off() : 
  QuartzBitmap_Output - unable to open file './HW/HW5/Legend_has_unused_levels.png'
Calls: <Anonymous> ... capture.output -> evalVis -> withVisible -> eval -> eval -> dev.off
Execution halted

I have no idea why this will happen and could anyone kindly give me some advice to fix it?

**Comment by npjc** [comment]
I'm not sure but I think you are trying to write to a place that doesn't exist.. can you post a minimal example that recapitulates your issue?

**Comment by BattaLiu** [comment]
This error happens every single time when I use ggsave(). 
E.g. ggsave(file='your_graph.png', path='./HW/HW5')

**Comment by BattaLiu** [comment]
Plus, the directory 'HW' lies in the same directory as my Rproject. This path works when I run the code.

**Comment by cathyxijuan** [comment]
I have noticed this.  When you knit it,  you working directory is set to the folder where you have your rmd file. So you really  don't need to specify your path.  Try it without the path argument

**Comment by BattaLiu** [comment]
@cathyxijuan Thank you very much! It works now, though I am a little bit confused. 
Why the working repository is set to the folder same as Rmd while different from my Rproject when kniting the file?
Can I change the underlying setup about working directory?

**Comment by npjc** [comment]
@BattaLiu  Yes you are trying to save to a directory `HW/HW5` _within_ the directory where the `.Rmd` is knit and since this doesn't exist you get a 'unable to open file' error. Note that if you are working interactively within a `.Rmd` then you must take care to keep track of your current working directory.

if this isn't clear consider the following in an example .Rmd file: `.Rmd` file:

```{r example-rmd-chunk}
library(ggplot2)
# filename way
ggplot(mtcars, aes(cyl, mpg)) + geom_point()
ggsave(filename = "cyl-vs-hwy.png")
# with an additional absolute path
ggplot(mtcars, aes(cyl, mpg)) + geom_point()
ggsave('cyl-vs-hwy-path.png', path = "example/absolute/path/Desktop")
# with an additional relative path
ggplot(mtcars, aes(cyl, mpg)) + geom_point()
ggsave('cyl-vs-hwy-path.png', path = "./Desktop/")
```

**Comment by cathyxijuan** [comment]
I am not sure either... I just noticed this because I use my own data to do the assignment.  Everytime I run the R code,  I will first manually set the working directory to the folder the rmd file is in.

**Comment by BattaLiu** [comment]
Yes, I think setting the working directory to the folder the rmd file is in is the safest way.

**Comment by jennybc** [comment]
This is an ongoing and global source of frustration.

The natural workflow within an RStudio project is to leave the top-level directory as your working directory.

And yet R markdown documents, by default, assume that working directory is the directory in which they live.

So these two things contradict each other.

My pragmatic advice is to set working directory to the directory where `.Rmd` lives, with the mouse of `setwd()` in the Console, while you are developing the `.Rmd`. Because once you click "Knit HTML" or use `rmarkdown::render()` that will be the default working directory.

Never set or change working directory within `.Rmd`.

**Comment by jennybc** [comment]
I have written a rant about this, with a possible solution here:

https://gist.github.com/jennybc/362f52446fe1ebc4c49f

**Comment by BattaLiu** [comment]
Thank you @jennybc , the pragmatic solution works.
However, I don't know how to use the possible solution you suggested. I have changed my .Rprofile, then try to add `path=file.path(PROJHOME, 'HW/HW5')` as option in ggsave(), but it doesn't work in knitting.
I am not sure whether my understanding is correct.

**Comment by jennybc** [comment]
@BattaLiu Can you be more specific?

Where is the `.Rprofile`? How are you knitting the file that contains `ggsave()`? What is working directory at that time? What error do you get when you knit?
