### ISSUE TITLE
Working directory pain

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#217]
Re: in-class discussion about what working directory should be:

  * the top-level directory of the RStudio Project?
  * the directory where `.R` or `.Rmd` lives

My answer: this is not an easy question to answer. There is no good and perfect solution.

Two resources (I'm happy for others to add more!):

  * Jenny's rant and kludgy solution: [Stop the working directory insanity gist](https://gist.github.com/jennybc/362f52446fe1ebc4c49f#file-2014-10-12_stop-working-directory-insanity-md)
  * Dean's package / function / vignette:
    - [`rsalad`](https://github.com/daattali/rsalad)
    - [`spinMyR()` function](https://github.com/daattali/rsalad/blob/master/R/spinMyR.R)
    - [`spinMyR` vignette](https://github.com/daattali/rsalad/blob/master/vignettes/spinMyR.md)

**Comment by daattali** [comment]
FYI in case anybody is interested: the function I have in `rsalad` is using a similar function to `knit` called `spin`. The function `spinMyR` is not a dropin replacement for `knitr::knit()`; rather, it is a replacement for `knitr::spin()`. The difference between `knit` and `spin` is that `knit` operated on a Rmarkdown (.Rmd) input, while `spin` uses R scripts as input (.R).

The reason that I say this is because if you just want a drop-in replacement for `knitr::knit()`, then that will not work. I made a newer package called [`ezrender`](https://github.com/daattali/ezrender) that has similar logic but supports both `knit` and `spin`.  **If you use knitr and are annoyed with the directories issue, the [`ezrender`](https://github.com/daattali/ezrender) package is what you want**, specifically the function `ezknit`.  I didn't advertise this package yet because it's very incomplete, but it does work, so you can use it if you want.  You can use `ezrender::ezknit()` instead of `knitr::knit()` and tell it what working directory to use and where to put figures (if you don't tell it these things, it figures out defaults which are smarter than the `knitr` defaults).

Not sure if that's useful to anyone, but now it's out there.
