### ISSUE TITLE
Latex woes when checking your package

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#240]
Would someone who experienced this please post details? So I can post a solution?

**Comment by csiu** [comment]
I was one of the people experiencing the "Latex woes" (*Note: it works for me now*) .... I'm using a Mac and here is what worked for me/what I learned:


----
When you hit Check & it complains along the lines of "\<package\>.sty not found", then you are missing a package and will need to install the latex package by e.g. `sudo tlmgr install <package>`

- You may need to update the package manager itself by e.g. `sudo tlmgr update --self`
- You may also need to (but probably not) update all the packages by e.g. `sudo tlmgr update --all`

----

When you hit Check & you get:

    fatal format file error; I'm stymied

then running any `pdflatex <file>.tex` command should not be able to run since [you may have been playing with the configuration, or have just installed a new version of latex](http://www.tex.ac.uk/FAQ-formatstymy.html). You will need to:

    fmtutil --all

- Note: I used `fmtutil --refresh` to "recreate only existing format files" (instead of all of them)

----

When you hit Check & you get something which contains "**Font ... =phvr8t**" e.g.:

    ! Font T1/phv/m/n/14.4=phvr8t at 14.4pt not loadable: Metric (TFM) file not found. 

you will need to install the helvetic.sty module:

     sudo tlmgr install helvetic

**Comment by jennybc** [comment]
Thanks, @csiu.

Can you clarify your OS and method of LaTeX installation? Ubuntu or Mac or ?? And I guess TeX Live? Because that affects who can use your solution.

**Comment by csiu** [comment]
Hi @jennybc,

I'm using Mac OS X 10.9.5 and have installed LaTeX via the smaller [BasicTeX from MacTex](https://tug.org/mactex/) which got placed into `/usr/local/texlive/2014basic/`. I also mainly rely on the [`tlmgr` - TeX Live package manager](https://www.tug.org/texlive/tlmgr.html) to do any installing/updating/removing of the tex packages.

**Comment by jennybc** [comment]
I'm not looking at any one specific error message. But here's general advice that could help.

You can specify `--no-manual` as an option to `R CMD check` to suppress the creation of the PDF manual.

In RStudio: *Tools > Project Options*, enter `--no-manual` in the field for "Check Package -- R CMD check additional options". That will presumably affect all calls triggered by RStudio menus.

If calling `devtools::check()` directly, you should be able to specify this option via the `build_args` argument.

It's best to actually read the errors/warnings and try to fix them for real, as @csiu did. But this could be a temporary workaround.

**Comment by KPdir** [comment]
I had some LateX related problem in class as well which we had fixed in the office hours. Unfortunately I did not document it - so can't really talk about it.  

However, I have a new  LateX related problem which may or may not be the same as the earlier problem. The workaround  ```--no-manual``` in ```R CMD check``` surely makes it go away but I haven't figured out the real problem yet. 

The details of **ERROR** are in this section below: 
```
* checking tests ...
  Running ‘testthat.R’ OK
* checking PDF version of manual ...
 WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... ERROR
* DONE
Status: 1 ERROR, 1 WARNING
```
From Hadley's book on packages:
>Checking PDF version of manual. Occassionally you’ll get an error when building the PDF manual. This is usually because the pdf is built by latex and you’ve forgotten to escape something. Debugging this is painful - your best bet is to look up the latex logs and combined tex file and work back from there to .Rd files then back to a roxygen comment. I consider any such failure to be a bug in roxygen2, so please let me know.

That lead me to look into this [stack overflow thread](http://stackoverflow.com/questions/10819959/diagnosing-r-package-build-warning-latex-errors-when-creating-pdf-version) and using ```R CMD Rd2pdf mypackage --no-clean``` as shown below:  
```
kmp:~/temp/foofactors:14:10 $ R CMD Rd2pdf ../foofactors  --no-clean
Hmm ... looks like a package
Converting Rd files to LaTeX 
Creating pdf output from LaTeX ...
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'Rd2.tex' failed.
Messages:
sh: /usr/local/bin/texi2dvi: No such file or directory
Output:

Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'Rd2.tex' failed.
Messages:
sh: /usr/local/bin/texi2dvi: No such file or directory
Output:

Error in running tools::texi2pdf()
You may want to clean up by 'rm -rf .Rd2pdf8383'
```
One of the answers in the thread perhaps refers to the situation that I have which is that ```texi2dvi``` is actually here ```/usr/bin/texi2dvi``` while R CMD looks for it ```/usr/local/bin/texi2dvi```.  I tried to add a symlink to it as suggested like so: 
```
cd /usr/local/bin
ln -s /usr/bin/texi2dvi
```
However, permission was denied in trying to add the symlink and I am having sudo'ing problems which I haven't figured out yet. I hope that part from the sudo'ing issues, the rest of the info here could help in mitigating the ```texi2dvi``` path problem.

**Comment by stevenpollack** [comment]
Ran into the same 
```
Font T1/phv/m/n/14.4=phvr8t at 14.4pt not loadable:
```
error as @csiu and the
```
sudo tlmgr install helvetic
```
did the trick.

Thank you!

**Comment by pachamaltese** [comment]
Hi

I have this issue in OSX Yosemite. My solution was to do this

1. Remove all the folders inside /usr/local/texlive
2. Download texlive basic 2016
3. From tex live utility reinstall helvetic, inconsolata

That made everything working again. 

Just a detail: Before this issue tex live utility was telling me to install texlive 2016 and I didn't do that. After that message roxygen2 started to fail building pdfs.
