### ISSUE TITLE
Error after using Check()

### ISSUE THREAD

**Issue by arunmarria** [STAT545-UBC/Discussion#241]
I tried creating the same foo package but I got an error after adding **test_fBind.R**. Error looked as follows

----------------------------------------------------------------------------------------
 ### ** Examples
> 
> fbind(iris$Species[c(1, 51, 101)], PlantGrowth$group[c(1, 11, 21)])
Error: could not find function "fbind"
Execution halted
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'testthat.R' OK
* DONE
Status: 1 ERROR

See
  'C:/Users/HP/Desktop/Demo/foo/foofactors.Rcheck/00check.log'
for details.

Error: Command failed (1)
In addition: Warning message:
@export [fbind.R#11]: may only span a single line 
Execution halted

Exited with status 1.

--------------------------------------------------------------------------------------------------

Any suggestions are welcome.

Thanks.

**Comment by jennybc** [comment]
I've already reported this to RStudio:

https://support.rstudio.com/hc/communities/public/questions/205901678-Too-many-newlines-in-roxygen-comments?locale=en-us

Get rid of the empty line between `#' @export` and `#' @examples`. That will fix the warning.

But you've got bigger problems. I think you need to run `document()` so that `fbind()` is listed as an exported function in the `NAMESPACE`.

**Comment by jennybc** [comment]
But I can't reproduce that warning about the extra line now? That is, I can have that line there and NOT get a warning.

**Comment by arunmarria** [comment]
I tried doing as suggested by you. It worked fine for me (no warnings and errors)
:)
