### ISSUE TITLE
Error using check() with pipeline

### ISSUE THREAD

**Issue by zhamel** [STAT545-UBC/Discussion#247]
I get the following error when I use the function `check()`:
When I do `check()` without putting any example I don't get an error but once I include the example I keep getting the same error.

Error in reorder_levels(factor(c("character", "hits", "your", "eyeballs",  : 
  could not find function "%>%"
Execution halted

My function reorder the factor levels based on their frequency and I used `%>%` in my function. 
Here is the code for my function:

```{r}
reorder_levels <- function(x){
  xdf <- dplyr::data_frame(x)
  count <- xdf %>% dplyr::group_by(x) %>% tally()
  factor(dplyr::reorder(count$x,count$n,dplyr::desc))
}
```

Other than this the function seem to work correctly!

**Comment by BernhardKonrad** [comment]
Did you check that the magrittr package is loaded when `%>%` is called?

**Comment by jennybc** [comment]
Yes, as @BernhardKonrad implies, the `%>%` operator is not built-in to R. Normally when you use it, it works because you have loaded `dplyr` via `library(dplyr)`. So you need to make it available to use it in your package. Using `%>%` in a package is a mildly controversial thing, but I do it and don't see a problem if you want to do it here in STAT 545.

My recommendation to use functions from other packages like so: `dplyr::group_by()` obviously will not work for `%>%`! So put this line in the roxygen header of some function in your package:

``` r
#' @importFrom dplyr %>%
```

It doesn't matter which function -- it will still make `%>%` available broadly within your package.

and run `document()`. That should cause `importFrom(dplyr,"%>%")` to appear in your `NAMESPACE` file.

BTW `dplyr` does not have a `reorder()` function. That comes from the `stats` package. So `dplyr:;reorder()` should be `stats::reorder()`, I think.

**Comment by zhamel** [comment]
Thank you both. It works now :) 
I had done a bit of all this but in the wrong place and/or wrong order...
