### ISSUE TITLE
difference between the readme and the vignette?

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#249]
I was just wondering what is the difference in content between the realm file and a vignette. Seems like they both hold the same type of documentation (according to what's in the class file) but they are saved in a different way? I just need some clarification on what the vignette should have beside some examples on how my function works

**Comment by jennybc** [comment]
Please see https://github.com/STAT545-UBC/Discussion/issues/246

**Comment by daattali** [comment]
Short answer: for our purposes, they're almost interchangeable. But they don't serve exactly the same purpose.

README is a file that should be the first thing a user sees when they go to a package, so it should give a description of what the package does, maybe how to install it, what are some usecases.  It's nice to include a README.md because if you go to a GitHub repo of a package then you immediately see it. For example, look at [dplyr on GitHub](https://github.com/hadley/dplyr/), if you scroll down below the files you'll see a nice document telling you the basics of dplyr.  It can be as detailed s you want, or it can just be a very quick overview of the package. README is usually viewed when you see a package on GitHub, but you don't really often access it from RStudio. README is not required.

Vignettes are a way to provide longer documentation or to show a usecase of how to use your package, showing all steps and going into detail. You can have multiple vignettes, each with its own topic. For example, look at the [vignettes for dplyr](https://github.com/hadley/dplyr/tree/master/vignettes) - there are several vignettes. An introduction vignette, a vignette about how to use window functions, a vignette about using databases, etc. If you type in R `browseVignettes("dplyr")`, it'll bring you to a page that lists all the vignettes.  Vignettes are more official in R.

If you have a complex package with different topics, it could make sense to have a general README that gives a high level introduction to the package, and write several vignettes, each describing a topic in detail.  But I don't think this makes sens for us right now.

Most of my packages are simple enough that I just provide a lot of details right in the README and go through working examples in the README. Since that's also the job of a vignette, I actually have my README and vignette being identical.  And that's totally fine!  [Here's a README for a package of mine](https://github.com/daattali/ggExtra) and [here's the vignette](https://github.com/daattali/ggExtra/blob/master/vignettes/overview.Rmd). They're identical.

So it's up to you how exactly you want to differentiate them. You could put the long documentation and working example in the vignette only, and have the README be short and only give a high level overview.



I'm not sure if that helped at all or if it was way too much rumbling.  Hadley has a book about package development and it may be worth seeing [what he has to say about README](http://r-pkgs.had.co.nz/release.html#readme) vs [vignettes](http://r-pkgs.had.co.nz/vignettes.html)  (it's an easy read, I recommend reading it , it will only take a couple minutes)

**Comment by bdacunha** [comment]
That was a perfect answer! thanks!!
