### ISSUE TITLE
can I change the package after I use use_package_doc()?

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#251]
I just uploaded my package to github and when I tried to install it in my computer it works, but I get a warning saying Warning in install.packages : package ‘randompic’ is not available (for R version 3.2.2)
But it does work when I use it.

Can I change the version of R to 3.2.1 in the description and then commit the changes? I tried using use_package_doc() and it says that I already have that package so I don't know how to change this.

**Comment by daattali** [comment]
You can certainly change the R version requirement in the DESCRIPTION file.

But that's not your problem here.  `install.packages()` is used to install packages from CRAN. Your package is on GitHub, not on CRAN. You can [attempt to submit it to CRAN](https://cran.r-project.org/submit.html) but that's a lengthy process and should only be done when your package is 100% done and actually useful.

Since your package is on GitHub, you can install it using `devtools::install_github(bdacunha/randompic)`

**Comment by bdacunha** [comment]
thanks Dean! I forgot about devtools::install_github()
