### ISSUE TITLE
How to count unique values in subgroups? 

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#258]
Hello,

First a question related to making my example: I wanted to creacte a data.frame with 2 variables (character or factor, doesn;t matter). 

```{r}
Var1 <- as.data.frame(c("A", "B", "C",  "B", "B", "D",  "D", "D", "A", "A"))
colour <- as.data.frame(c("blue", "blue", "blue", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red"))
> df <- bind_cols(Var1, colour)

> df
Source: local data frame [10 x 2]

   c("A", "B", "C", "B", "B", "D", "D", "D", "A", "A")
                                                (fctr)
1                                                    A
2                                                    B
3                                                    C
4                                                    B
5                                                    B
6                                                    D
7                                                    D
8                                                    D
9                                                    A
10                                                   A
Variables not shown: c("blue", "blue", "blue", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red") (fctr)

#ARRRRRGGGGGGG -> rename variables (see Questions below)
> df <- df %>%
+ rename(Var1 = `c("A", "B", "C", "B", "B", "D", "D", "D", "A", "A")`, colour=`c("blue", "blue", "blue", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red")`)
> df
Source: local data frame [10 x 2]

     Var1 colour
   (fctr) (fctr)
1       A   blue
2       B   blue
3       C   blue
4       B yellow
5       B yellow
6       D yellow
7       D yellow
8       D yellow
9       A    red
10      A    red

```

1) WHY is the name of the column not `Var1` and `colour` in the beginning (i.e., before I use `dplyr`'s `rename()`, but the actual vector I assigned to the object/dataframe?
2) How can I sidepass this?
3) How can I rename these, now? Because `dplyr` really does not like any quotation marks in the title! And even when I get the name via `names()`, it escaped every " (as in `\"`) but when I copied pasted these `R` escaped names into `dplyr`'s `rename()` function, it didn't like that either....
-> OK 3) I just found out by pure chance: I have to use the `R` language quotation mark.... NOT the normal single quotation mark

__NOW to my original question for which I made this example:__

How do I go about it, if I want to know how many `unique()` letters are part of each colour?

i.e. what I would like to get is
blue  = 3 (A, B, C)
yellow = 2 (B, B, D, D, D)
red = 1 (A, A)

I tried:
```{r}
> df <- df %>% 
+   group_by(colour) %>% 
+   length(unique())
Error in is.factor(x) : argument "x" is missing, with no default

> df <- df %>%
+ group_by(colour) %>%
+ summary(n_distinct)
Error in length(ll) > maxsum : 
  comparison (6) is possible only for atomic and list types


```
The only way I can think of right now is the code intensive filtering of each group and storing each group into a new object of itself and then calling `unique()` on the variable
```
> (df_yellow <- df %>%
+ filter(colour=="yellow"))
Source: local data frame [5 x 2]

    Var1 colour
  (fctr) (fctr)
1      B yellow
2      B yellow
3      D yellow
4      D yellow
5      D yellow
> (length(unique(df_yellow$Var1)))
[1] 2
```
and then storing each information somehow into a new object..
That sound just aweful depending on your dataset....

Any suggestions?

Thanks
Anna

**Comment by jennybc** [comment]
First, let's discuss your pain creating the `df` example. Here is how I would do it: define both variables at once in a new data frame.

``` r
df <-
  data.frame(Var1 = c("A", "B", "C",  "B", "B", "D",  "D", "D", "A", "A"),
             colour = c("blue", "blue", "blue", "yellow", "yellow", "yellow",
                        "yellow", "yellow", "red", "red"))
df
#>    Var1 colour
#> 1     A   blue
#> 2     B   blue
#> 3     C   blue
#> 4     B yellow
#> 5     B yellow
#> 6     D yellow
#> 7     D yellow
#> 8     D yellow
#> 9     A    red
#> 10    A    red
```

Your use of `as.data.frame()`, instead of `data.frame()`, coupled with mixing base and `dplyr` functions (`as.data.frame`() is from base, whereas `bind_cols()` is from `dplyr`), had some unintended downsides! That's how you managed to create the self-named `Var1` factor and to bring the individual colors in as variables.

Re: terminology, since it's good to know the accpeted names for stuff ... To complete your tricky renaming task, you correctly used **backticks** or **back quotes**. And they are necessary when an object bears a name that includes characters that are normally "off limits", such as quotes. You can read more [here](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Quotes.html).

Now for your main question. How to get or count the unique values of letter for each color? Two main problems: you don't specify `Var1` as the variable to look at for unique values. Also, you want to call `dplyr::summarize()`, not `base::summary()`.

``` r
library(dplyr)
df %>%
  group_by(colour) %>%
  summarize(n_unique = n_distinct(Var1))
#> Source: local data frame [3 x 2]
#> 
#>   colour n_unique
#>   (fctr)    (int)
#> 1   blue        3
#> 2    red        1
#> 3 yellow        2
```

The fact that you assigned your first unsuccessful attempt back into `df` probably didn't help. You want to be really careful with that because it's easy to overlook that and have mistakes and frustration really compound themselves.

**Comment by ahippman** [comment]
The devil is in the detail... in `R` even more true...
I know this is so rudimentary but somehow it is still such a huge obstacle for me. I also need to get used to the possibility to directly name new variables as you did in
```{r}
... summarize(n_unique = n_distinct(Var1))
```
I would have executed just
```{r}
... summarize(n_distinct(Var1)
```
and then renamed the variable...

Thanks a lot for taking the time!

Cheers
Anna
