### ISSUE TITLE
curl and wget don't exist for windows?

### ISSUE THREAD

**Issue by AdrianLJones** [STAT545-UBC/Discussion#263]
I'm working on HW09 and trying to download the gapminder dataset from github using the shell.

However I get the following for both commands:
> C:\Users\Adrian\Documents\STAT545a\adrian_jones\Homework\Homework09>curl /?
> 'curl' is not recognized as an internal or external command,
> operable program or batch file.

> C:\Users\Adrian\Documents\STAT545a\adrian_jones\Homework\Homework09>wget /?
> 'wget' is not recognized as an internal or external command,
> operable program or batch file.

I've done very quick bit of googling and it sounds like they don't exist on windows, is this as intended for the Rtools thing we installed?

I did find [another command](http://superuser.com/questions/299754/wget-curl-alternative-native-to-windows) `bitsadmin` which, despite the worries of the people on the thread seems to be present on my windows 10 computer.  Is that what the pros of this class would suggest I use?

Thanks for help before I start a wild goose chase down the rabbit hole to tilt at the windmills of syntax.

Adrian

**Comment by jennybc** [comment]
Sigh. The annual Windows sh!t. 😕

I had some hope that Rtools would take care of this but now that you mention it, I have no reason to hope that Rtools will provide either wget or curl. Here's what I *think* it provides?

> basename, cat, cmp, comm, cp, cut, date, diff, du, echo, expr, gzip, ls, make, makeinfo, mkdir, mv, rm, rsync, sed, sh, sort, tar, texindex, touch and uniq ... zip and unzip

https://github.com/STAT545-UBC/Discussion/issues/230#issuecomment-155233443

So either you need to install more Unix stuff or just use R to download the file. I highly recommend the latter. Or even use R to locate the delimited file locally (remember, it comes with the gapminder package) and copy it from there.

But IF you install more software, you can look at some installation instructions we used last year:

http://stat545-ubc.github.io/automation02_windows.html

However, I notice that won't get you `curl` or `wget` either. Here's how to get `wget` on Windows:

http://superuser.com/questions/25538/how-to-download-files-from-command-line-in-windows-like-wget-is-doing

And curl:

http://curl.haxx.se/download.html

But seriously consider using R.

**Comment by samhinshaw** [comment]
@jennybc may not officially recommend this, but *if* this is a concern for you *in the long term* you may seriously want to consider linux.  I hope that @namanpaul can attest to this.  [Virtual machines](virtualbox.org) and dual booting both have their benefits and drawbacks, but Ubuntu has made linux so incredibly accessible, it's not a huge gap anymore. 

Of course a mac is always nicer, but linux is free...
![125px-tux svg](https://cloud.githubusercontent.com/assets/14186005/11387971/392a6c80-92e5-11e5-8da8-9e376992e2c4.png)

**Comment by jennybc** [comment]
I'm definitely not anti-linux! I used to do exactly this. I tried both dual boot (Windows and Linux) and running one OS as primary and the other in a VM. It was pretty high friction. I didn't enjoy spending the weekend, e.g., trying to connect to a wireless printer. So long ago I went with Mac OS as the best compromise between Unix and normal life.

But things have gotten much easier, since then. I highly recommend getting OFF OF WINDOWS. Dual booting is quite inconvenient, so I would only seriously consider [1] committing to wholeheartedly to linux and/or [2] using a virtual machine / Docker.

**Comment by sho-87** [comment]
I've been using linux on and off for years now and I always end up switching back to windows due to numerous compatibility and stability problems. The headache of windows is not as great as the headache that comes with linux it seems

anyway, I believe curl comes as part of git bash so you can give that a try?

**Comment by AdrianLJones** [comment]
Okay, thanks, I think for this project I'll stick to R and look at other options another time.
