### ISSUE TITLE
Pandoc error solution

### ISSUE THREAD

**Issue by zhamel** [STAT545-UBC/Discussion#270]
I have been getting this error when I try to `render()` my report in the last step of the pipeline

**"pandoc version 1.12.3 or higher is required and was not found"**

The pipeline was working in R but not with the shell.

Here is the link to a [solution](http://stackoverflow.com/questions/28432607/pandoc-version-1-12-3-or-higher-is-required-and-was-not-found-r-shiny) in case anyone else run into the same problem ... I am not sure I really understand what's goinf on but it works!! 

Hopefully this can avoid some frustration!

**Comment by jennybc** [comment]
Good find. I love that your SO searching skills are coming along nicely 😁.

It sounds like this env var is already set in the usual ways you do things but is somehow not set when you are rending from the shell. It's probably another weird Windows thing, like people struggling with packages not being found because `.libPaths()` is inexplicably different. This SO solution explicitly sets that env var, in case it's not getting picked up my default.
