### ISSUE TITLE
general makefile confusion

### ISSUE THREAD

**Issue by molliejmcdowell** [STAT545-UBC/Discussion#275]
I'm confused about what is supposed to go in the Makefile. If I have an R script that writes multiple tsv files and png files, do I add them all to the Makefile separately? Even though they are from the same R script?

Also, do I write all of those tsv and png files again in the rmarkdown report?

**Comment by jennybc** [comment]
The usual way to handle multiple output like you describe is to give them very regular names and then use a __pattern rule__ in the Makefile. Precisely so you don't have to handle them all separately.

We definitely didn't cover this, so don't feel on the hook for it. For example, you could throw away a lot of data do that you're only working with, say, 3 countries or continents or whatever, so that explicit listing is not completely awful.

For anyone who wants to look into pattern rules:

  * Karl Broman mentions briefly in his tutorial: <http://kbroman.org/minimal_make/>
  * The GNU Make manual goes into some detail: <http://www.gnu.org/software/make/manual/make.html#Pattern-Rules>

**Comment by molliejmcdowell** [comment]
great thanks! I'm not going to try that tonight. I just wrote everything... it seems to work
