### ISSUE TITLE
Shiny in a package

### ISSUE THREAD

**Issue by Haycen** [STAT545-UBC/Discussion#282]
Hello,

I have included a Shiny app within a package. All the shiny code is in `inst` folder and I run the shiny app with this function:
```
runSQUID <- function() {
  appDir <- system.file("shiny-squid", "myapp", package = "SQUID")
  if (appDir == "") {
    stop("Could not find example directory. Try re-installing `squid`.", call. = FALSE)
  }
  shiny::runApp(appDir, display.mode = "normal")
}
```

Now, I would like to create a new function in my package that basically use some of the functions that are used by Shiny and that are in `inst` folder.

I'm wondering what would be the best way to do so?

Should I source these functions? Apparently it's not really recommended to source function in a R package.

Thanks

**Comment by daattali** [comment]
Good job creating a shiny app and knowing where to put it!  Did you by any chance get this idea and code from [my blog post](http://deanattali.com/2015/04/21/r-package-shiny-app/)? I ask because that's the exact error message that I use in my blog...

To answer your question: you're correct that you shouldn't be `source()`-ing in your R package.  It sounds like those functions should just be exported package functions if you want to use them in your package, instead of only defining them in your app.  So make a new file under the `R/` folder and make them the same as any other function in your package.  Am I missing something, is there any reason you're not doing that?

**Comment by Haycen** [comment]
Hi Dean,

Yes I used your blog to create my package. Actually, you suggested me this solution. 

So yeah that's what I was thinking but will it be possible for my shiny app to access to these functions if they are in the folder `R/`?

thanks

**Comment by daattali** [comment]
Since this Shiny app is inside your package, I assume it uses many other functions from your app, no?  

Just load your package at the top of your shiny app so that your app can use the package. Or better yet, don't actually load the package, but refer to the functions you need by namespacing them (using the `package::function()` syntax). [Here's an example of me doing this](https://github.com/daattali/ggExtra/blob/master/inst/examples/ggMarginal/server.R#L97) - it's a Shiny app inside my ggExtra package, and in order to call a function from the package, I use `ggExtra::ggMarginal()`

**Comment by Haycen** [comment]
Yes my app uses many functions. But so far I declared my functions in the same folder where my app is located. 

This option should work for me as well.

Thanks

**Comment by daattali** [comment]
I don't quite understand. If your app is using functions from your package but those functions are declared in the app's folder, then they're not exported by the package. Or do you mean that you literally copied the functions so they're both in the R folder and in your app folder?

It's be easier to tell what's going on if I could see your package, but it doesn't look like it's on GitHub.  You should come to the office hours or talk to me for one minute after class

**Comment by Haycen** [comment]
I would love to talk more about this with you but I'm presently away and I won't be back in Vancouver before late December.

Yes, indeed, this package is quite complicated. Basically, when I created this app I didn't have in mind to include it in a package. The app is relatively big so I subset the ui.R and sever.R in multiple files (functions) that I source when the app starts. 

Now, I decided to add this app in a package because I want to make it public so people will be able to use it.

If you want to have a look to the code, I added you as a collaborator.

Thanks

**Comment by daattali** [comment]
I see it now, it does look very complicated. But I still think that if these are functions that both your package and shiny app need to use, simply write them in your R folder and refer to them as `SQUID::function()`.

FYI I see you're using a lot of `require()` statements. I strongly recommend you use `library()` instead. You can Google for the difference and why that's recommended.

Also, I see in your app you're installing packages if they don't exist. If a package is inside the `Imports:` in the DESCRIPTION, then that's not necessary, those packages will be installed when your package is installed.

Lastly, you might want to look at [shinyjs](https://github.com/daattali/shinyjs) to make your JavaScript communication easier

**Comment by aammd** [comment]
hello gentlemen,
Late to this party, but I'm just wondering if you considered using [`rappdirs`](https://github.com/hadley/rappdirs) to move the shiny app to a user's computer, rather than keeping it in the `/inst` directory of the package? I'm trying to learn to use `rappdirs` and this seems like a good use case. Just curious.

**Comment by Haycen** [comment]
Hi @aammd 

No I haven't consider `rappdirs`. I'll try to have a look at it. But so far I'm quite happy by just putting my app in the `/inst` folder

Thanks

**Comment by daattali** [comment]
I haven't heard of it, but based on my one-minute read of the README I'm not sure if it will have benefits in this case.  But good to know about
