### ISSUE TITLE
Make students' private repo public 

### ISSUE THREAD

**Issue by ehsanmok** [STAT545-UBC/Discussion#286]
Hi

I just wanted to ask if it's possible to make our private course repo public?

Regards
Ehsan

**Comment by oganm** [comment]
Do you ask this from a technical standpoint or do you want to know if you are allowed to make it public?

**Comment by ehsanmok** [comment]
The latter :)

**Comment by dchiu911** [comment]
@jennybc has addressed this before, so maybe she will chime in if anything has changed this year

**Comment by jennybc** [comment]
I would prefer you not make it public in its exact form, because I think it might be just too tempting for future students to do too much copy/paste. Do you really want to "flip the switch" on the entire repo, as it is today? I'm hoping you will say there are specific projects you want to make public and we can find a way forward that is less likely to create future plagiarism problems.

**Comment by ehsanmok** [comment]
Fair enough! I just wanted to make sure what the policy is. 

Thanks
Ehsan
