### ISSUE TITLE
Homework 10

### ISSUE THREAD

**Issue by dylandong12** [STAT545-UBC/Discussion#293]
If I don't want to work on the ``Combine gapminder and data from geonames`` section, am I supposed to solve all the three questions in the ``But I’m tired of GDP`` section?

**Comment by jennybc** [comment]
@aammd

**Comment by aammd** [comment]
No, those are just suggestions. The idea is to use the rOpenSci packages we looked at to get **two** different datasets, then combine them.  This can be any two datasets that you think are interesting, obtained from `rplos`, `rebird` or `geonames`. The combined dataset you create should be "moderately large" -- about `gapminder`-sized (In other words, no need to make it huge, also don't do something that's only a few lines!)

Depending on what you choose, the task of actually merging will be easy or hard. And i have only tried out a small set of the possible options. That's why i think this exercise is a bit "more" than the first one.

**Comment by dylandong12** [comment]
OK. Thanks!
