### ISSUE TITLE
write a message as a shiny output?

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#296]
Hello,

I'm currently working with a different dataset to build my shiny app.. so far, everything works, but sometimes the selections I make (talking in bc liquor store terms: a country doesn't have beers) in order to filter the table or to create the plot, don't have any results, and I get an "error"... is there anyway in which I can tell R that when there are no results from the selection it should say something like : your selection didn't give any results. Try again?

Thanks!

Brenda

**Comment by daattali** [comment]
If you look at the ideas for improving the BC liquor app, your question is actually one of the problems I mentioned as something that can be tackled.  

From the homework:
> The app currently behaves strangely when the user selects filters that return 0 results. For example, try searching for wines from Belgium. There will be an empty plot and empty table generated, and there will be a warning message in the R console. Try to figure out why this warning message is appearing, and how to fix it.
>
>- **Hint:** The problem happens because renderPlot() and renderTable() are trying to render an empty dataframe. To fix this issue, the filtered reactive expression should check for the number of rows in the filtered data, and if that number is 0 then return NULL instead of a 0-row dataframe.


So what I suggest in the hint is one way to fix this: when filtering the data, if you see there are 0 rows, then return NULL. And in your `renderPlot` and `renderTable` functions, you can check if simply render nothing if the data is NULL. Something like this

``` 
output$plot <- renderPlot({
  if (is.null(data)) {
    return(NULL)
  }
  # the rest of the plotting code
})
# similarly for renderTable
```

Another one of my suggestions in the homework is to include a message that always tells you how many results were found.  You would do this with a `textOutput()`+`renderText()`, for example

```
shinyApp(
  ui = fluidPage(textOutput("text1")),
  server = function(input, output) {
    output$text1 <- renderText({"hello"})
  }
)
```

Of course you should put some logic in your `textOutput` that will use the number of results.

If you want to only sometimes show the output and sometimes hide it, you can use the `hide()` and `show()` functions from the `shinyjs` package. Here's an example of showing and hiding a `textOutput` based on an input which can get you started

```
shinyApp(
    ui = fluidPage(
        useShinyjs(),
        numericInput("num","Number", 5),
        textOutput("text1")
    ),
    server = function(input, output) {
        output$text1 <- renderText({
            if (input$num < 5) {
                hide("text1")
            } else {
                show("text1")
            }
            paste0("The number is ", input$num)
        })
    }
)
```

There is also another option in Shiny using the `validate()` function. You can read about it [on the Shiny help page](http://shiny.rstudio.com/articles/validation.html).  Using the validate function lets you show a custom "error" message when the data in a render function isn't good enough to use.  I personally never use the validate function because I find it strange, but you can use it.

Hopefully some of this helped and you can try to figure out how to solve your problem now

**Comment by bdacunha** [comment]
Thanks Dean, I will work with that!
