### ISSUE TITLE
RStudio unresponsive - won't open at all!

### ISSUE THREAD

**Issue by zhamel** [STAT545-UBC/Discussion#297]
So.. I have been trying to reopen RStudio for 2 days, but it won't!

When I finished my HW, I ran it one more time after saving everything and RStudio become "not responsive" as I was running my Makefile. I have had this before, but then it goes away really quickly (less than 30 sec). But it just stayed like this so I forced RStudio to close. And now, I am not able to reopen it. I tried using the shell but I am really not used to it and so I didn't manage to make it work. Any suggestions?

I also tried to update the current version, or to uninstall RStudio but it won't let me either.

Any help would be VERY VERY appreciated!

**Comment by jennybc** [comment]
I have no idea what's going on. But I will be seeing someone from RStudio in person on Tuesday and will ask about this, assuming it's not yet resolved.

**Comment by BernhardKonrad** [comment]
When you try to open RStudio from the shell, what happens?

A short-term alternative would be to try a different IDE like [rkward](https://rkward.kde.org/). The IAM/Math IT can also provide you with an remote RStudio server, which lets you access RStudio in the browser.

**Comment by zhamel** [comment]
When I open it from the Desktop icon or from the shell, it seems to be running as a 'background process' instead of an 'app' (according to the task manager)... but honestly I don't really know what it means  and whether/how I can change this!

Thanks Bernhard, I will go to the Math IT today..

**Comment by zhamel** [comment]
Ok.. so.. I just spent 2 hours with the MATH IT people and nothing! We still can't run or even uninstall RStudio. I guess I will do the peer review without running the files, but if things keep not working what can I do so I can start the last homework?

**Comment by jennybc** [comment]
Can you tell me what OS you're on? What have you tried to uninstall? In what way does that not work?

**Comment by daattali** [comment]
Sorry for all the trouble you're going through, that sounds very strange. Hope you can get it fixed. 

Regarding doing the last homework: you don't NEED Rstudio to develop Shiny apps, but it certainly makes it easier because of the "Run App" button.  But you can use other text editor to develop your code, such as the one @BernhardKonrad suggested.  To actually run your app, I assume that rkward doesn't have the Run App button, which means you'll have to run your Shiny app manually every time you want to test it. To run your app without the "Run App" button, just run the command `shiny::runApp("path/to/Shiny/app/dir")`. Of course you'd need to change the directory and use the actual directory where your Shiny app lives. When you run that command, your Shiny app will be launched in your browser.  I hope that works

**Comment by zhamel** [comment]
Thanks @daattali , I will try this.. 

@jennybc 
I am using Windows.. I have tried tried to uninstall RStudio both from the 'control panel' and from the uninstall.exe file but in both cases it does not respond!

**Comment by BernhardKonrad** [comment]
Sorry to hear that you're still having technical issues. Does your supervisor have a virtual machine that you can access? I'm not sure what you tried with the IT folks, but a couple years ago The set up RStudio Server on this virtual machine, no install required from my part. I just had to go to a website and login to the remote machine with my Math account credentials.

Of course, getting it fixed on your own machine is a priority. Hope one of the offered workarounds lets you finish the course work for now.

**Comment by jennybc** [comment]
@zhamel can you go to office hours today?

**Comment by zhamel** [comment]
Yes, I am planning on coming at 11am.

**Comment by jennybc** [comment]
Can you try deleting this directory:

```
C:\Users\Kevin\AppData\Local\RStudio-Desktop
```

making any logical substitutions for your system?

Alternatively, are you able to delete the entire folder enclosing RStudio (vs. running the un-installer)? So delete:

```
C:\Program Files\RStudio
```

assuming you installed in the default location.

**Comment by zhamel** [comment]
We (Kieran) fixed it :+1: 

We had to manually delete the RStudio folder and re-install it ... but still don't know what happened!

Thank you everyone for the help.

**Comment by BernhardKonrad** [comment]
Awesome!!

**Comment by jennybc** [comment]
Just to be clear, did deletion of the enclosing directory

`C:\Program Files\RStudio`

resolve it? And then you were able to re-install?

**Comment by ksamuk** [comment]
Yes! However, when Zoe tried to use the windows command prompt, it did not work here (perhaps the command prompt needed to be elevated to admin? not clear). Anyway, we ended up rebooting, deleting the directory via the windows explorer, and then reinstalling.

**Comment by jennybc** [comment]
@kevinushey Thanks for the tip that ultimately solved this. Tagging you in case you care to know that this did get resolved and how.

**Comment by daattali** [comment]
I think she said all of this happened after RStudio froze and she tried to quit it. So maybe there's some kind of a lock file that got corrupted or somehow in a weird state and prevented any other session to open...? That would also explain why it was difficult to delete the folder, because the file could have been "in use". Just a thought. Glad it's done
