### ISSUE TITLE
Shiny help

### ISSUE THREAD

**Issue by lmguzman** [STAT545-UBC/Discussion#304]
Hey, Im trying to finish the shiny homework, and one of the tasks I chose was to add a colour input and pass that as an argument to ggplot. Ive been able to add the colour input but Im having problems rendering the ggplot. 

This is what I have on the UI function:
colourInput("colInput","Colour",value = 'black', showColour = c("background"))

This is that I have for the ggplot on the server function: 
output$coolplot <- renderPlot({
			if (is.null(filtered())) {
				return()
			}
			ggplot(filtered(), aes(Alcohol_Content)) +
				geom_histogram(aes_string(fill = input$colInput))
		})

I would appreciate any help!

**Comment by oganm** [comment]
Please
* Try to have a reproducible example of your problem
* Format your code with ` tags

The problem with your code is at `aes_string()`. You use `aes` when you want an aesthetic element rely on some collumn in your frame. You use `aes_string()` when said collumn is subject to change. You are not trying to do either of those things here so all you have to do is get rid of that part. Below is a working example (though I changed filter to be a static data.frame rather than a reactive) Critical part is `geom_histogram(fill = input$colInput)`


``` r

library(shinyjs)
library(shiny)

ui <- shinyUI(fluidPage(
   

   sidebarLayout(
      sidebarPanel(
          colourInput("colInput","Colour",value = 'black', showColour = c("background"))
      ),
      
      mainPanel(
         plotOutput("coolplot")
      )
   )
))

server <- shinyServer(function(input, output) {
   filtered = data.frame(Alcohol_Content = c(1,2,3,4,5))
    
   output$coolplot <- renderPlot({
       if (is.null(filtered)) {
           return()
       }
       ggplot(filtered, aes(Alcohol_Content)) +
           geom_histogram(fill = input$colInput)
   })
})

shinyApp(ui = ui, server = server)


```
