### ISSUE TITLE
Git Tab

### ISSUE THREAD

**Issue by MarliseHofer** [STAT545-UBC/Discussion#340]
The Git tab has disappeared on my Rstudio! In tools, global options, git, I still seem to have the correct git set up. But I don't know why the tab is gone!

**Comment by jennybc** [comment]
Did you upgrade anything about your system?

**Comment by oganm** [comment]
Or did you open your project that is also a git repository or did you open rstudio by double clicking a script in a subdirectory?

**Comment by jennybc** [comment]
@oganm Have you seen that before?! If so, interesting.

**Comment by MarliseHofer** [comment]
I figured it out! I restarted everything and then opened the project again and it worked. I think I was trying to open the Rmd file directly. Thanks!!

**Comment by oganm** [comment]
@jennybc Isn't that expected behaviour? If you open Rstudio by double clicking a file and not a project, Rstudio will not show the git tab. When I was writing that I was thinking it would be fine if said file wasn't in a subdirectory since Rstudio will be able to see git and proceed and usual but it seems like as a rule of thumb, you don't get the git tab unless you open the project

**Comment by jennybc** [comment]
@oganm This is a great example of how my own usage of RStudio leaves me utterly blind to this. If I double click on an Rmd file, it just opens in one of the Projects I already have open. Furthermore, I would never double click on an Rmd file; I always work in Projects. So I quit all instances of RStudio 😱 and double-clicked on an Rmd file for the sake of Science and this thread. Sure enough, I see what you mean.
