### ISSUE TITLE
ggplot colour fill for country by country_colors - won't work?

### ISSUE THREAD

**Issue by supersonicole** [STAT545-UBC/Discussion#381]
I've basically copied and pasted Jenny's code with a bit of tweaking for hw_05.
But for some reason the colour fill by country_colors just won't work. 

I've probably been staring at this code for the past hour now to the point that I just want to tear my face/hair off... :frowning_face:  If anyone spots my mistake in the code, my hair will be very grateful... (and so will I!) 

```
library(gapminder)
suppressPackageStartupMessages(library(tidyverse))

gap_north_am <- gapminder %>%
        filter(country %in% c("Canada", "United States","Mexico", 
                                "Cuba", "Panama", "Costa Rica")) %>% 
        select(country, year, lifeExp, pop)

gap_north_am %>% 
        ggplot(aes(x = year, y = lifeExp, fill = country)) +
        scale_fill_manual(values = country_colors) +
        geom_point(aes(size = pop), pch = 19)
```

**Comment by philstraforelli** [comment]
Hi,

The problem is with `pch = 19`, which is black-filled icon. If you use `pch = 21` instead, the colours will show.

**Comment by supersonicole** [comment]
Literally right before you wrote this, it hit me that if I changed "fill" to "color", pch = 19 would work. And then I realized that "fill" will work with pch = 21, but not pch = 19.

Yikes... I had no idea that there were such subtleties regarding [shapes](http://stat545.com/img/r.pch.pdf) and what aesthetics they would only work with! Will treat shapes with the appropriate amount of caution from this day forth...

Thank you @philstraforelli. Much appreciated.

**Comment by jennybc** [comment]
Thanks again @philstraforelli!

@supersonicole If you check out this cheatsheet of plotting symbols (http://stat545.com/img/r.pch.pdf), you'll notice some just have an outline whereas some are filled. Now, it's not entirely obvious which regions are controlled by the color vs fill aesthetic (because red versus yellow is not a rule), but @philstraforelli is definitely right that you will need to be strategic in combining your choice of `pch` and your use of color vs fill.
