### ISSUE TITLE
putting Exercise 1 in a new folder

### ISSUE THREAD

**Issue by NarayanGopinathan** [STAT545-UBC/Discussion#543]
I have done my Exercise 1 for Assignment 1, and put it in a new folder. However, even though it worked in its original READ.me format outside of the new folder, it does not work in the folder. Can anyone help me? @545a-2019-20-team
[(https://github.com/STAT545-UBC-hw-2019-20/stat545-hw-NarayanGopinathan/blob/master/Assignment-1/Exercise-1)](url)

**Comment by vincenzocoia** [comment]
Hi @NarayanGopinathan, I think you mean to say that the `Exercise-1` file does not show up in rendered format below the list of files on GitHub. It turns out that GitHub will only show a rendered version of a file below the list of files if the filename is `README.md`.

So, if you have a file named `README.md` in your `Assignment-1` folder, you'll see it when you navigate to that folder on GitHub. 

By the way, I noticed that your `Exercise-1` file is the same as your `README.md` file in the root of your homework repository. This content should only go in the README, not elsewhere.

**Comment by NarayanGopinathan** [comment]
Got it, thanks!

**Comment by vincenzocoia** [comment]
@NarayanGopinathan feel free to close this issue if you consider the issue solved!
