### ISSUE TITLE
Copy and pasting files into Repos?

### ISSUE THREAD

**Issue by AdrianLJones** [STAT545-UBC/Discussion#96]
I have a bit of time to work on my private readme file, but don't have the repo yet.
So I figured I'd make a readme file in a public repo and work on it and then copy paste that into the private repo when I can.

Is there any reason in github or RStudio that this might blow up in my face?

I assume the meta data of the number of commits and date stamps and branches won't follow the file to its new location, but I figure for the purpose of this particular file, that shouldn't be too important.

Thanks,

Adrian

**Comment by ksamuk** [comment]
Hi Adrian!

This should be fine. The readme is just a `.md` file, so you can freely move it from one repo to another.

**Comment by samhinshaw** [comment]
Adrian, 

I was spending some time playing around with this as well, trying to clone the git repository ggplot2-tutorial (https://github.com/jennybc/ggplot2-tutorial) into my own public repo.  Doing so via git will retain previous version history (see https://github.com/samhinshaw/ggplot2-tutorial).

I would imagine copy & paste works too, but if you want some extra practice, you can run these commands in shell. 
First copy your public repo into a new directory. 
`git clone <public repo with readme.md you're practicing with>`

Then set this clone to sync with your new private repo rather than the old public one
`git remote set-url origin <new private repo url>`

If anyone else has clarifications, they are welcome!  
See also: 
`git clone --help`
http://stackoverflow.com/questions/18200248/cloning-a-repo-from-someone-elses-github-and-pushing-it-to-a-repo-on-my-github

Cheers, 
Sam
